/*
 * File: app/store/ActivityJsonPTreeStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.store.ActivityJsonPTreeStore', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'LogisticSMP.model.ActivityModel',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ActivityJsonPTreeStore',
            model: 'LogisticSMP.model.ActivityModel',
            data: [
                {
                    task: 'adipisci',
                    id: 162,
                    project_id: 939,
                    parent_id: 247,
                    name: 'asperiores',
                    start_date: '11/1/2009',
                    end_date: '12/27/2005'
                },
                {
                    task: 'quisquam',
                    id: 630,
                    project_id: 483,
                    parent_id: 100,
                    name: 'officiis',
                    start_date: '10/12/2012',
                    end_date: '1/18/2006'
                },
                {
                    task: 'iure',
                    id: 491,
                    project_id: 483,
                    parent_id: 27,
                    name: 'mollitia',
                    start_date: '5/1/2007',
                    end_date: '2/15/2002'
                },
                {
                    task: 'neque',
                    id: 318,
                    project_id: 80,
                    parent_id: 442,
                    name: 'expedita',
                    start_date: '11/20/2010',
                    end_date: '10/25/2012'
                },
                {
                    task: 'et',
                    id: 755,
                    project_id: 456,
                    parent_id: 923,
                    name: 'nemo',
                    start_date: '2/22/2002',
                    end_date: '8/27/2007'
                },
                {
                    task: 'cum',
                    id: 439,
                    project_id: 900,
                    parent_id: 808,
                    name: 'omnis',
                    start_date: '12/7/2005',
                    end_date: '7/10/2002'
                },
                {
                    task: 'deleniti',
                    id: 50,
                    project_id: 888,
                    parent_id: 8,
                    name: 'nulla',
                    start_date: '7/21/2011',
                    end_date: '12/12/2011'
                },
                {
                    task: 'voluptatum',
                    id: 285,
                    project_id: 785,
                    parent_id: 128,
                    name: 'illum',
                    start_date: '10/1/2014',
                    end_date: '5/16/2008'
                },
                {
                    task: 'ut',
                    id: 920,
                    project_id: 421,
                    parent_id: 885,
                    name: 'ipsam',
                    start_date: '3/4/2014',
                    end_date: '11/16/2012'
                },
                {
                    task: 'et',
                    id: 276,
                    project_id: 165,
                    parent_id: 361,
                    name: 'accusantium',
                    start_date: '9/8/2002',
                    end_date: '3/14/2006'
                },
                {
                    task: 'enim',
                    id: 599,
                    project_id: 117,
                    parent_id: 867,
                    name: 'ut',
                    start_date: '7/2/2007',
                    end_date: '3/27/2005'
                },
                {
                    task: 'molestias',
                    id: 909,
                    project_id: 259,
                    parent_id: 730,
                    name: 'fuga',
                    start_date: '5/27/2003',
                    end_date: '11/16/2010'
                },
                {
                    task: 'quia',
                    id: 513,
                    project_id: 940,
                    parent_id: 814,
                    name: 'dolores',
                    start_date: '6/14/2001',
                    end_date: '2/2/2006'
                },
                {
                    task: 'iure',
                    id: 349,
                    project_id: 450,
                    parent_id: 419,
                    name: 'sint',
                    start_date: '8/6/2013',
                    end_date: '5/23/2007'
                },
                {
                    task: 'repellat',
                    id: 189,
                    project_id: 944,
                    parent_id: 775,
                    name: 'non',
                    start_date: '5/1/2007',
                    end_date: '2/1/2007'
                },
                {
                    task: 'unde',
                    id: 581,
                    project_id: 649,
                    parent_id: 987,
                    name: 'quia',
                    start_date: '12/12/2002',
                    end_date: '2/11/2013'
                },
                {
                    task: 'quasi',
                    id: 123,
                    project_id: 274,
                    parent_id: 289,
                    name: 'sapiente',
                    start_date: '4/10/2004',
                    end_date: '1/27/2008'
                },
                {
                    task: 'sed',
                    id: 945,
                    project_id: 837,
                    parent_id: 291,
                    name: 'ut',
                    start_date: '9/14/2013',
                    end_date: '12/14/2001'
                },
                {
                    task: 'eos',
                    id: 490,
                    project_id: 276,
                    parent_id: 918,
                    name: 'possimus',
                    start_date: '11/24/2001',
                    end_date: '8/15/2010'
                },
                {
                    task: 'magni',
                    id: 134,
                    project_id: 832,
                    parent_id: 169,
                    name: 'est',
                    start_date: '10/21/2014',
                    end_date: '9/26/2007'
                },
                {
                    task: 'eos',
                    id: 726,
                    project_id: 313,
                    parent_id: 129,
                    name: 'non',
                    start_date: '4/21/2002',
                    end_date: '8/11/2010'
                },
                {
                    task: 'reprehenderit',
                    id: 55,
                    project_id: 495,
                    parent_id: 337,
                    name: 'soluta',
                    start_date: '8/8/2002',
                    end_date: '3/21/2007'
                },
                {
                    task: 'eaque',
                    id: 680,
                    project_id: 28,
                    parent_id: 54,
                    name: 'voluptatibus',
                    start_date: '11/25/2011',
                    end_date: '7/9/2011'
                },
                {
                    task: 'est',
                    id: 293,
                    project_id: 300,
                    parent_id: 24,
                    name: 'unde',
                    start_date: '8/4/2007',
                    end_date: '7/23/2006'
                },
                {
                    task: 'praesentium',
                    id: 900,
                    project_id: 168,
                    parent_id: 997,
                    name: 'assumenda',
                    start_date: '9/5/2006',
                    end_date: '4/6/2004'
                },
                {
                    task: 'eaque',
                    id: 725,
                    project_id: 322,
                    parent_id: 535,
                    name: 'esse',
                    start_date: '3/4/2005',
                    end_date: '2/27/2009'
                },
                {
                    task: 'dicta',
                    id: 800,
                    project_id: 880,
                    parent_id: 760,
                    name: 'sit',
                    start_date: '1/26/2014',
                    end_date: '2/5/2008'
                },
                {
                    task: 'occaecati',
                    id: 180,
                    project_id: 701,
                    parent_id: 522,
                    name: 'est',
                    start_date: '1/17/2004',
                    end_date: '5/26/2002'
                },
                {
                    task: 'sint',
                    id: 118,
                    project_id: 999,
                    parent_id: 985,
                    name: 'nobis',
                    start_date: '5/12/2011',
                    end_date: '5/14/2009'
                },
                {
                    task: 'est',
                    id: 230,
                    project_id: 448,
                    parent_id: 370,
                    name: 'odio',
                    start_date: '6/27/2011',
                    end_date: '8/3/2007'
                }
            ],
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});