/*
 * File: app/store/BarCharOverViewStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.store.BarCharOverViewStore', {
    extend: 'Ext.data.Store',

    requires: [
        'LogisticSMP.model.BarChartOverviewModel',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'BarCharOverViewStore',
            model: 'LogisticSMP.model.BarChartOverviewModel',
            data: [
                {
                    id: 184,
                    name: 'similique',
                    Current: 903.54,
                    progress: 965.98
                },
                {
                    id: 819,
                    name: 'ab',
                    Current: 601.73,
                    progress: 404.67
                },
                {
                    id: 895,
                    name: 'animi',
                    Current: 776.13,
                    progress: 192.45
                },
                {
                    id: 850,
                    name: 'assumenda',
                    Current: 186.15,
                    progress: 391.76
                },
                {
                    id: 685,
                    name: 'non',
                    Current: 569.79,
                    progress: 398.63
                },
                {
                    id: 681,
                    name: 'iusto',
                    Current: 653.43,
                    progress: 4.71
                },
                {
                    id: 728,
                    name: 'veritatis',
                    Current: 803.98,
                    progress: 105.21
                },
                {
                    id: 498,
                    name: 'aut',
                    Current: 319.42,
                    progress: 328.58
                },
                {
                    id: 649,
                    name: 'voluptatem',
                    Current: 524.43,
                    progress: 990.02
                },
                {
                    id: 558,
                    name: 'placeat',
                    Current: 375.98,
                    progress: 468.14
                },
                {
                    id: 436,
                    name: 'et',
                    Current: 886.08,
                    progress: 85.78
                },
                {
                    id: 672,
                    name: 'et',
                    Current: 151.11,
                    progress: 592.83
                },
                {
                    id: 321,
                    name: 'maiores',
                    Current: 39.42,
                    progress: 5.73
                },
                {
                    id: 28,
                    name: 'ad',
                    Current: 729.12,
                    progress: 737.16
                },
                {
                    id: 317,
                    name: 'aliquam',
                    Current: 443.86,
                    progress: 654.53
                },
                {
                    id: 315,
                    name: 'suscipit',
                    Current: 273.64,
                    progress: 677.73
                },
                {
                    id: 986,
                    name: 'autem',
                    Current: 299,
                    progress: 142.3
                },
                {
                    id: 432,
                    name: 'aut',
                    Current: 296.42,
                    progress: 342.11
                },
                {
                    id: 865,
                    name: 'ipsam',
                    Current: 45.57,
                    progress: 394.08
                },
                {
                    id: 445,
                    name: 'animi',
                    Current: 600.65,
                    progress: 553.05
                }
            ],
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});