/*
 * File: app/store/ProjectStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.store.ProjectStore', {
    extend: 'Ext.data.Store',

    requires: [
        'LogisticSMP.model.ProjectModel',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ProjectStore',
            model: 'LogisticSMP.model.ProjectModel',
            data: [
                {
                    id: 867,
                    year: 246,
                    name: 'voluptatum',
                    progress: 915.9,
                    current: 623.57,
                    budget: 503.75
                },
                {
                    id: 355,
                    year: 486,
                    name: 'repellat',
                    progress: 760.38,
                    current: 232.84,
                    budget: 589.65
                },
                {
                    id: 860,
                    year: 651,
                    name: 'illum',
                    progress: 148.95,
                    current: 98.55,
                    budget: 329.64
                },
                {
                    id: 314,
                    year: 584,
                    name: 'voluptatem',
                    progress: 602.66,
                    current: 614.63,
                    budget: 374.24
                },
                {
                    id: 157,
                    year: 210,
                    name: 'at',
                    progress: 216.73,
                    current: 38.65,
                    budget: 849.14
                },
                {
                    id: 835,
                    year: 803,
                    name: 'omnis',
                    progress: 881.35,
                    current: 986.14,
                    budget: 139.55
                },
                {
                    id: 251,
                    year: 291,
                    name: 'ipsa',
                    progress: 621.77,
                    current: 428.55,
                    budget: 27.13
                },
                {
                    id: 536,
                    year: 134,
                    name: 'quis',
                    progress: 339.31,
                    current: 955.29,
                    budget: 787.54
                },
                {
                    id: 294,
                    year: 611,
                    name: 'harum',
                    progress: 873.41,
                    current: 609.65,
                    budget: 135.18
                },
                {
                    id: 378,
                    year: 357,
                    name: 'excepturi',
                    progress: 405.76,
                    current: 666.63,
                    budget: 39.25
                },
                {
                    id: 849,
                    year: 398,
                    name: 'debitis',
                    progress: 778.57,
                    current: 812.05,
                    budget: 732.75
                },
                {
                    id: 481,
                    year: 27,
                    name: 'eaque',
                    progress: 906.16,
                    current: 333.75,
                    budget: 124.97
                },
                {
                    id: 489,
                    year: 728,
                    name: 'doloribus',
                    progress: 761.56,
                    current: 605.95,
                    budget: 767.4
                },
                {
                    id: 428,
                    year: 378,
                    name: 'est',
                    progress: 674.39,
                    current: 969.31,
                    budget: 538.64
                },
                {
                    id: 400,
                    year: 461,
                    name: 'dignissimos',
                    progress: 103.64,
                    current: 166.72,
                    budget: 356.67
                },
                {
                    id: 548,
                    year: 821,
                    name: 'exercitationem',
                    progress: 20.19,
                    current: 936.5,
                    budget: 396.96
                },
                {
                    id: 182,
                    year: 785,
                    name: 'quaerat',
                    progress: 714.61,
                    current: 526.54,
                    budget: 152.32
                },
                {
                    id: 892,
                    year: 365,
                    name: 'dolor',
                    progress: 185.82,
                    current: 232.02,
                    budget: 70.37
                },
                {
                    id: 435,
                    year: 424,
                    name: 'rerum',
                    progress: 862.54,
                    current: 646.01,
                    budget: 569.02
                },
                {
                    id: 378,
                    year: 679,
                    name: 'aut',
                    progress: 228.34,
                    current: 719.33,
                    budget: 441
                }
            ],
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});