/*
 * File: app/store/StrategicModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.store.StrategicModel', {
    extend: 'Ext.data.Store',
    alias: 'store.strategicmodel',

    requires: [
        'LogisticSMP.model.StrategicModel',
        'Ext.data.proxy.Memory'
    ],
    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
        	groupField: 'year',
        	model: 'LogisticSMP.model.StrategicModel',
            autoLoad: true,
            proxy: {
                type: 'ajax',
                url: 'manage_strategic.php?type=all',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});
    
//    constructor: function(cfg) {
//        var me = this;
//        cfg = cfg || {};
//        me.callParent([Ext.apply({
//            groupField: 'year',
//            storeId: 'StrategicModel',
//            model: 'LogisticSMP.model.StrategicModel',
//            data: [
//                {
//                    id: 371,
//                    name: 'sunt',
//                    year: 2013
//                },
//                {
//                    id: 287,
//                    name: 'odio',
//                    year: 1983
//                },
//                {
//                    id: 930,
//                    name: 'tenetur',
//                    year: 1972
//                },
//                {
//                    id: 430,
//                    name: 'expedita',
//                    year: 1998
//                },
//                {
//                    id: 478,
//                    name: 'amet',
//                    year: 1984
//                },
//                {
//                    id: 519,
//                    name: 'fugit',
//                    year: 1999
//                },
//                {
//                    id: 878,
//                    name: 'tempore',
//                    year: 1979
//                },
//                {
//                    id: 506,
//                    name: 'qui',
//                    year: 1976
//                },
//                {
//                    id: 586,
//                    name: 'doloremque',
//                    year: 1970
//                },
//                {
//                    id: 275,
//                    name: 'quia',
//                    year: 1982
//                },
//                {
//                    id: 665,
//                    name: 'numquam',
//                    year: 2009
//                },
//                {
//                    id: 845,
//                    name: 'culpa',
//                    year: 1999
//                },
//                {
//                    id: 965,
//                    name: 'maiores',
//                    year: 1995
//                },
//                {
//                    id: 33,
//                    name: 'quis',
//                    year: 2001
//                },
//                {
//                    id: 350,
//                    name: 'modi',
//                    year: 1985
//                },
//                {
//                    id: 473,
//                    name: 'magni',
//                    year: 2002
//                },
//                {
//                    id: 363,
//                    name: 'doloribus',
//                    year: 2012
//                },
//                {
//                    id: 226,
//                    name: 'nostrum',
//                    year: 1979
//                },
//                {
//                    id: 204,
//                    name: 'dolor',
//                    year: 1985
//                },
//                {
//                    id: 519,
//                    name: 'eum',
//                    year: 1998
//                },
//                {
//                    id: 229,
//                    name: 'quia',
//                    year: 1986
//                },
//                {
//                    id: 211,
//                    name: 'quo',
//                    year: 1972
//                },
//                {
//                    id: 594,
//                    name: 'autem',
//                    year: 1988
//                },
//                {
//                    id: 109,
//                    name: 'provident',
//                    year: 2006
//                },
//                {
//                    id: 24,
//                    name: 'ea',
//                    year: 2003
//                },
//                {
//                    id: 643,
//                    name: 'et',
//                    year: 1975
//                },
//                {
//                    id: 939,
//                    name: 'quisquam',
//                    year: 1996
//                },
//                {
//                    id: 786,
//                    name: 'cupiditate',
//                    year: 2005
//                },
//                {
//                    id: 764,
//                    name: 'et',
//                    year: 1997
//                },
//                {
//                    id: 420,
//                    name: 'qui',
//                    year: 1975
//                }
//            ],
//            proxy: {
//                type: 'memory'
//            }
//        }, cfg)]);
//    }
//});