/*
 * File: app/store/StstrategicStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.store.StstrategicStore', {
    extend: 'Ext.data.Store',

    requires: [
        'LogisticSMP.model.ProjectModel',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'StstrategicStore',
            model: 'LogisticSMP.model.ProjectModel',
            data: [
                {
                    id: 299,
                    year: 906,
                    name: 'explicabo',
                    progress: 172.87,
                    current: 417.39,
                    budget: 965.37
                },
                {
                    id: 530,
                    year: 928,
                    name: 'et',
                    progress: 293,
                    current: 852.05,
                    budget: 951.95
                },
                {
                    id: 869,
                    year: 574,
                    name: 'quis',
                    progress: 75.25,
                    current: 116.27,
                    budget: 441.67
                },
                {
                    id: 814,
                    year: 620,
                    name: 'dicta',
                    progress: 964.4,
                    current: 871.65,
                    budget: 195.53
                },
                {
                    id: 618,
                    year: 98,
                    name: 'natus',
                    progress: 339.34,
                    current: 54.39,
                    budget: 327.16
                },
                {
                    id: 784,
                    year: 769,
                    name: 'aut',
                    progress: 897.21,
                    current: 960.11,
                    budget: 609.4
                },
                {
                    id: 628,
                    year: 462,
                    name: 'aut',
                    progress: 242.2,
                    current: 986.1,
                    budget: 681.75
                },
                {
                    id: 143,
                    year: 65,
                    name: 'est',
                    progress: 187.47,
                    current: 952.45,
                    budget: 466
                },
                {
                    id: 631,
                    year: 415,
                    name: 'deleniti',
                    progress: 664.61,
                    current: 255.53,
                    budget: 388.04
                },
                {
                    id: 114,
                    year: 54,
                    name: 'qui',
                    progress: 936.02,
                    current: 324.33,
                    budget: 934.66
                },
                {
                    id: 744,
                    year: 638,
                    name: 'maiores',
                    progress: 433.41,
                    current: 143.38,
                    budget: 266.55
                },
                {
                    id: 65,
                    year: 682,
                    name: 'voluptates',
                    progress: 66.34,
                    current: 223.64,
                    budget: 102.09
                },
                {
                    id: 83,
                    year: 769,
                    name: 'occaecati',
                    progress: 699.08,
                    current: 617.07,
                    budget: 13.33
                },
                {
                    id: 695,
                    year: 515,
                    name: 'distinctio',
                    progress: 459.43,
                    current: 655.82,
                    budget: 298.17
                },
                {
                    id: 350,
                    year: 929,
                    name: 'nobis',
                    progress: 186.59,
                    current: 384.06,
                    budget: 297.4
                },
                {
                    id: 960,
                    year: 825,
                    name: 'at',
                    progress: 339.88,
                    current: 173.23,
                    budget: 271.33
                },
                {
                    id: 112,
                    year: 555,
                    name: 'molestias',
                    progress: 669.14,
                    current: 352.93,
                    budget: 28.49
                },
                {
                    id: 842,
                    year: 228,
                    name: 'aut',
                    progress: 279.93,
                    current: 282.61,
                    budget: 680.61
                },
                {
                    id: 313,
                    year: 877,
                    name: 'est',
                    progress: 969.7,
                    current: 989.18,
                    budget: 997.79
                },
                {
                    id: 748,
                    year: 239,
                    name: 'aut',
                    progress: 496.47,
                    current: 538.39,
                    budget: 876.3
                },
                {
                    id: 118,
                    year: 172,
                    name: 'facere',
                    progress: 237.01,
                    current: 845.65,
                    budget: 597.43
                },
                {
                    id: 371,
                    year: 784,
                    name: 'accusantium',
                    progress: 69.74,
                    current: 387.92,
                    budget: 876.38
                },
                {
                    id: 982,
                    year: 611,
                    name: 'corporis',
                    progress: 925.35,
                    current: 168.49,
                    budget: 278.15
                },
                {
                    id: 885,
                    year: 173,
                    name: 'rem',
                    progress: 584.02,
                    current: 319.88,
                    budget: 490.03
                },
                {
                    id: 951,
                    year: 510,
                    name: 'explicabo',
                    progress: 134.59,
                    current: 453.74,
                    budget: 949.59
                },
                {
                    id: 679,
                    year: 947,
                    name: 'soluta',
                    progress: 543.69,
                    current: 261.58,
                    budget: 419.93
                },
                {
                    id: 182,
                    year: 596,
                    name: 'recusandae',
                    progress: 294.71,
                    current: 831.36,
                    budget: 77.29
                },
                {
                    id: 909,
                    year: 163,
                    name: 'dolor',
                    progress: 531.19,
                    current: 903.85,
                    budget: 880.19
                },
                {
                    id: 389,
                    year: 194,
                    name: 'voluptatem',
                    progress: 898.87,
                    current: 978.44,
                    budget: 686.35
                },
                {
                    id: 66,
                    year: 456,
                    name: 'ipsum',
                    progress: 321.91,
                    current: 388.59,
                    budget: 6.76
                }
            ],
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});