/*
 * File: app/store/YearArrayStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.store.YearArrayStore', {
    extend: 'Ext.data.Store',
    
    requires: [
               'LogisticSMP.model.YearModel',
               'Ext.data.proxy.Ajax',
               'Ext.data.reader.Json'
           ],

           constructor: function(cfg) {
               var me = this;
               cfg = cfg || {};
               me.callParent([Ext.apply({
                   //storeId: 'MyJsonStore1',
                   model: 'LogisticSMP.model.YearModel',
                   autoLoad: true,
                   proxy: {
                       type: 'ajax',
                       url: 'year.php',
                       reader: {
                           type: 'json'
                       }
                   }
               }, cfg)]);
           }
});