/*
 * File: app/view/Overview.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.view.Overview', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.overview',

    requires: [
        'LogisticSMP.view.OverviewViewModel',
        'Ext.chart.PolarChart',
        'Ext.chart.series.Gauge',
        'Ext.chart.series.sprite.PieSlice',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar',
        'Ext.chart.interactions.PanZoom'
    ],

    viewModel: {
        type: 'overview'
    },
    itemId: 'contentPanel1',
    anchorSize: '100% 20%',
    title: 'หน้าหลัก',
    titleAlign: 'center',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'panel',
            anchor: '100% 50%',
            flex: 1,
            margins: '0 10 10 0',
            height: '',
            collapseFirst: false,
            collapsible: false,
            titleAlign: 'center',
            layout: {
                type: 'hbox',
                align: 'stretchmax',
                pack: 'center'
            },
            items: [
			//1
                {
                    xtype: 'polar',
                    flex: 1,
                    height: 198,
                    ui: 'light',
                    width: 208,
                    insetPadding: 30,
                    store: 'GaugeStore',
                    title: 'ระยะเวลาตามแผนงาน ',
					titleAlign: 'center',
					shadow: true,
					animation: true,
					
                    //titleCollapse: true,
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
					axes: {
                        //title: 'ระยะเวลาตามแผนงาน ',
                        type: 'numeric',
                        position: 'gauge'
                    },
                    series: {
                        type: 'gauge',
                        field: 'overview',
                        donut: 50,
						//needle: true,
						//needleWidth: 5,
						sectors: [
							{
								end: 35,
								label: 'ช้า',
								color: '#a61187'
							},
							{
								end: 75,
								label: 'ปกติ.',
								color: '#a66111'
							},
							{
								label: 'ไวกว่า',
								color: '#a66111'
							}
						]
                    }
                },
				{
                    xtype: 'polar',
                    flex: 1,
                    ui: 'light',
                    title: 'ความคืบหน้ากิจกรรม',
					titleAlign: 'center',
					shadow: true,
					animation: true,
					insetPadding: 30,
					ui: 'light',
					colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    store: 'GaugeStore',
                    axes: {
                        type: 'numeric',
                        position: 'gauge',
                        /* maximum: 250,
                        majorTickSteps: 2,
                        renderer: function (v) {
                            if (v === 0) return 'ช้า';
                            if (v === 125) return 'ปกติ';
                            if (v === 250) return 'ไวกว่า';
                            return ' ';
                        } */
                    },
                    series: {
                        type: 'gauge',
                        field: 'project',
                        donut: 50,
						//needle: true,
						//needleWidth: 5,
						sectors: [
							{
								end: 35,
								label: 'ช้า',
								color: '#a61187'
							},
							{
								end: 75,
								label: 'ปกติ.',
								color: '#a66111'
							},
							{
								label: 'ไวกว่า',
								color: '#a66111'
							}
						]
                    }
                },
				{
                    xtype: 'polar',
                    flex: 1,
                    ui: 'light',
                    title: 'การเบิกจ่ายงบประมาณ',
					titleAlign: 'center',
					shadow: true,
					animation: true,
					ui: 'light',
					insetPadding: 30,
					colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    store: 'GaugeStore',
                    axes: {
                        //title: 'Temp',
                        type: 'numeric',
                        position: 'gauge',
                        /* maximum: 250,
                        majorTickSteps: 2,
                        renderer: function (v) {
                            if (v === 0) return 'ช้า';
                            if (v === 125) return 'ปกติ';
                            if (v === 250) return 'ไวกว่า';
                            return ' ';
                        } */
                    },
                    series: {
                        type: 'gauge',
                        field: 'budget',
                        donut: 50,
						//needle: true,
						sectors: [
							{
								end: 35,
								label: 'ช้า',
								color: '#a61187'
							},
							{
								end: 75,
								label: 'ปกติ.',
								color: '#a66111'
							},
							{
								label: 'ไวกว่า',
								color: '#a66111'
							}
						]

                    }
                },
            ]
        },
        {
            xtype: 'panel',
            flex: 2,
            collapsible: false,
            title: 'ภาพรวมความก้าวหน้ารายยุทธศาสตร์',
            titleAlign: 'center',
            layout: {
                type: 'vbox',
                align: 'stretchmax'
            },
            dockedItems: [
                {
                    xtype: 'cartesian',
                    flex: -1,
                    dock: 'top',
                    height: 429,
                    margin: '5 5 5 5',
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    store: 'BarCharOverViewStore',
                    axes: [
                        {
                            type: 'category',
                            fields: [
                                'name'
                            ],
                            grid: true,
                            label: {
                                rotate: {
                                    degrees: -45
                                }
                            },
                            title: 'ยุทธศาสตร์',
                            position: 'bottom'
                        },
                        {
                            type: 'numeric',
                            renderer: function(label, layout, lastLabel) {
                                return 	label+' %';
                            },
                            fields: [
                                'Current',
                                'progress'
                            ],
                            grid: {
                                odd: {
                                    fill: '#e8e8e8'
                                }
                            },
                            maximum: 100,
                            minimum: 0,
                            position: 'left',
                            title: 'ความก้าวหน้า %'
                        }
                    ],
                    series: [
                        {
                            type: 'bar',
                            title: [
                                'ความก้าวหน้า',
                                'งบประมาณ'
                            ],
                            xField: 'name',
                            yField: [
                                'Current',
                                'progress'
                            ],
                            stacked: false,
//add by woody
							tooltip: {
								trackMouse: true,
								style: 'background: #fff',
								renderer: function (storeItem, item) {
									console.log(storeItem);
									console.log(item);
									var bar = item.series.getTitle()[Ext.Array.indexOf(item.series.getYField(), item.field)];
									this.setHtml(bar + ' ของ  ' + storeItem.get('name') + ' เป็นจำนวน  ' + storeItem.get(item.field) + '%');
									//bar + ' ของ  ' + storeItem.get('name') + ' เป็นจำนวน  ' + storeItem.get(item.field) + '%'
								}
							}
                        }
                    ],
                    interactions: [
                        {
                            type: 'panzoom'
                        }
                    ],
//add by woody
					legend: {
						docked: 'bottom'
					}
                }
            ]
        }
    ]

});