/*
 * File: app/view/StrategicModelsViewModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.view.StrategicModelsViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.strategicmodels',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        strategicModels: {
            model: 'LogisticSMP.model.StrategicModel',
            data: [
                {
                    id: 143,
                    name: 'aut',
                    year: 1980
                },
                {
                    id: 421,
                    name: 'quia',
                    year: 1974
                },
                {
                    id: 518,
                    name: 'quis',
                    year: 2008
                },
                {
                    id: 415,
                    name: 'officia',
                    year: 1986
                },
                {
                    id: 726,
                    name: 'aperiam',
                    year: 1986
                },
                {
                    id: 541,
                    name: 'et',
                    year: 1985
                },
                {
                    id: 6,
                    name: 'in',
                    year: 1986
                },
                {
                    id: 785,
                    name: 'ut',
                    year: 1983
                },
                {
                    id: 803,
                    name: 'voluptate',
                    year: 2005
                },
                {
                    id: 831,
                    name: 'adipisci',
                    year: 2013
                },
                {
                    id: 789,
                    name: 'qui',
                    year: 1998
                },
                {
                    id: 109,
                    name: 'consequuntur',
                    year: 2007
                },
                {
                    id: 647,
                    name: 'error',
                    year: 2004
                },
                {
                    id: 863,
                    name: 'quia',
                    year: 2007
                },
                {
                    id: 743,
                    name: 'itaque',
                    year: 1999
                },
                {
                    id: 337,
                    name: 'explicabo',
                    year: 1970
                },
                {
                    id: 292,
                    name: 'velit',
                    year: 1982
                },
                {
                    id: 510,
                    name: 'tempore',
                    year: 1974
                },
                {
                    id: 516,
                    name: 'officiis',
                    year: 1989
                },
                {
                    id: 371,
                    name: 'molestias',
                    year: 1985
                },
                {
                    id: 396,
                    name: 'autem',
                    year: 2010
                },
                {
                    id: 58,
                    name: 'sunt',
                    year: 1989
                },
                {
                    id: 238,
                    name: 'est',
                    year: 1987
                },
                {
                    id: 571,
                    name: 'modi',
                    year: 1983
                },
                {
                    id: 981,
                    name: 'recusandae',
                    year: 1992
                },
                {
                    id: 688,
                    name: 'dolor',
                    year: 1976
                },
                {
                    id: 37,
                    name: 'molestiae',
                    year: 1971
                },
                {
                    id: 442,
                    name: 'tempore',
                    year: 2010
                },
                {
                    id: 847,
                    name: 'natus',
                    year: 2003
                },
                {
                    id: 635,
                    name: 'sit',
                    year: 2005
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});