/*
 * File: app/view/StstrategicTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.view.StstrategicTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ststrategictab',

    requires: [
        'LogisticSMP.view.OverviewViewModel1',
        'LogisticSMP.view.OverviewViewController1',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar',
        'Ext.chart.interactions.PanZoom',
        'Ext.chart.Legend',
        'Ext.XTemplate'
    ],

    controller: 'ststrategictab',
    viewModel: {
        type: 'ststrategictab'
    },
    itemId: 'contentPanel2',
    anchorSize: '100% 20%',
    title: 'งบประมาณ',
    titleAlign: 'center',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            anchor: '100% 50%',
            margins: '0 10 10 0',
            height: 73,
            collapseFirst: false,
            collapsible: false,
            title: 'ยุทธศาสตร์',
            layout: {
                type: 'hbox',
                align: 'stretchmax',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'combobox',
                    flex: 1,
                    margin: '5 250 5 250',
                    fieldLabel: 'เลือกยุทธศาสตร์ที่ตอ้งการดู',
                    labelAlign: 'right',
                    labelWidth: 200,
                    displayField: 'name',
                    store: 'StstrategicStore',
                    valueField: 'id',
                    listeners: {
                        select: {
                            fn: 'onComboboxSelect',
                            scope: 'controller'
                        }
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            flex: -1,
            height: 'Ext.getBody().getViewSize().height',
            collapsible: false,
            title: 'งบประมาณ',
            titleAlign: 'center',
            layout: {
                type: 'vbox',
                align: 'stretchmax'
            },
            dockedItems: [
                {
                    xtype: 'cartesian',
                    flex: -1,
                    dock: 'top',
                    height: 618,
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    store: 'BarCharOverViewStore',
                    flipXY: true,
                    axes: [
                        {
                            type: 'category',
                            fields: [
                                'name'
                            ],
                            grid: true,
                            label: {
                                rotate: {
                                    degrees: -45
                                }
                            },
                            position: 'left',
                            title: 'โครงการ'
                        },
                        {
                            type: 'numeric',
                            renderer: function(label, layout, lastLabel) {
                                return 	label+' %';
                            },
                            fields: [
                                'Current',
                                'progress'
                            ],
                            grid: true,
                            majorTickSteps: 10,
                            maximum: 100,
                            minimum: 0,
                            title: 'เปอร์เซนต์ความก้าวหน้า',
                            position: 'bottom'
                        }
                    ],
                    series: [
                        {
                            type: 'bar',
							title: [
                                'ความก้าวหน้า ปัจจุบัน',
                                'ความก้าวหน้า คงเหลือ'
                            ],
                            xField: 'name',
                            yField: [
                                'Current',
                                'progress'
                            ],
							//add by woody
							tooltip: {
								trackMouse: true,
								style: 'background: #fff',
								renderer: function (storeItem, item) {
									console.log(storeItem);
									console.log(item);
									var bar = item.series.getTitle()[Ext.Array.indexOf(item.series.getYField(), item.field)];
									this.setHtml(bar + ' ของ  ' + storeItem.get('name') + ' เป็นจำนวน  ' + storeItem.get(item.field) + '%');
									//bar + ' ของ  ' + storeItem.get('name') + ' เป็นจำนวน  ' + storeItem.get(item.field) + '%'
								}
							}
                        }
                    ],
                    interactions: [
                        {
                            type: 'panzoom'
                        }
                    ],
					legend: {
						docked: 'bottom'
					},
					listeners: {
                        itemclick: 'onCartesianItemClick'
                    }
                }
            ]
        }
    ],

    onCartesianItemClick: function(series, item, event, eOpts) {
            console.log(item);
            console.log(series);
            console.log(event);
            console.log(eOpts);

    }

});