/*
 * File: app/model/ProjectModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.model.ProjectModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Number',
        'Ext.data.field.Date'
    ],
/*
    {
	id: "1",
	strategic_id: "1",
	strategy_id: "1",
	name: "project",
	seq: "1",
	start_date: "0000-00-00",
	end_date: "0000-00-00",
	progress: "0",
	budget: "0",
	strategic_name: "sfsdfsdf",
	strategy_name: "Test ยุทธศาสตร์ 1"
	}
*/
    fields: [
        {
            //type: 'int',
            name: 'id'
        },
        {
            //type: 'int',
            name: 'strategic_id'
        },
        {
            //type: 'int',
            name: 'strategy_id'
        },
        {
            //type: 'string',
            name: 'name'
        },
        {
            //type: 'int',
            name: 'seq'
        },
        {
            //type: 'date',
            name: 'start_date'
        },
        {
            //type: 'date',
            name: 'end_date'
        },
        {
            //type: 'float',
            name: 'progress'
        },
        {
            //type: 'float',
            name: 'budget'
        },
        {
           // type: 'string',
            name: 'strategy_name'
        },
        {
         //   type: 'string',
            name: 'strategic_name'
        }
        
    ]
});