/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'GaugeModel',
        'BarChartOverviewModel',
        'ProjectModel',
        'StstrategicModel',
        'ModelProject',
        'StrategicModel',
        'StrategyModel',
        'ActivityModel',
        'MainActivityModel',
        'YearModel'
    ],
    stores: [
        'GaugeStore',
        'BarCharOverViewStore',
        'ProjectStore',
        'StstrategicStore',
        'StrategicModel',
        'ProjectModels',
        'StrategyModel',
        'ActivityModel',
        'MainActivityModel',
        'ActivityJsonPTreeStore',
        'YearArrayStore'
    ],
    views: [
        'MainView',
        'Overview',
        'StstrategicTab',
        'ProjectTab',
        'Data.MainTabData',
        'Strategic2',
        'Data.ProjectTab1',
        'Data.ProjectTab2',
        'Data.ProjectTab4',
        'Data.ProjectTab3',
        'TreeGrid',
        'Data.ProjectTab5',
        'Window.Form.Add.Strategic',
        'StrategicModels',
        'Window.Form.Add.Strategy',
        'Window.Form.Add.Project'
    ],
    name: 'LogisticSMP',

    launch: function() {
        Ext.create('LogisticSMP.view.MainView');
    }

});
