/* auto generated by architect */ 
Ext.theme.addManifest([
    {
        "ui": "neutral",
        "xtype": "button"
    },
    {
        "ui": "neutral",
        "xtype": "button"
    },
    {
        "ui": "neutral",
        "xtype": "button"
    },
    {
        "ui": "confirm",
        "xtype": "button"
    },
    {
        "ui": "confirm",
        "xtype": "button"
    },
    {
        "ui": "confirm",
        "xtype": "button"
    },
    {
        "ui": "decline",
        "xtype": "button"
    },
    {
        "ui": "decline",
        "xtype": "button"
    },
    {
        "ui": "decline",
        "xtype": "button"
    },
    {
        "ui": "neutral",
        "xtype": "panel"
    },
    {
        "ui": "neutral",
        "xtype": "panel"
    }
]);