/*
 * File: app/view/Window/Form/Add/Activity.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.view.Window.Form.Add.Activity', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowformaddactivity',

    requires: [
        'LogisticSMP.view.Window.Form.Add.StrategicViewModel4',
        'LogisticSMP.view.Window.Form.Add.StrategicViewController4',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.toolbar.Breadcrumb',
        'Ext.button.Button'
    ],

    controller: 'windowformaddactivity',
    viewModel: {
        type: 'windowformaddactivity'
    },
    reference: 'form',
    height: 468,
    minHeight: 150,
    minWidth: 250,
    width: 750,
    bodyPadding: 10,
    title: 'Edit StrategicModel',
    modal: true,

    items: [
        {
            xtype: 'combobox',
            width: 745,
            fieldLabel: 'Strategic',
            displayField: 'name',
            store: 'StrategicModel',
            valueField: 'id',
            listeners: {
                select: 'onComboboxStrategicSelect'
            }
        },
        {
            xtype: 'combobox',
            width: 745,
            fieldLabel: 'Strategy',
            displayField: 'name',
            store: 'StrategyModel',
            valueField: 'id',
            listeners: {
                select: 'onComboboxStrategySelect'
            }
        },
        {
            xtype: 'combobox',
            width: 745,
            fieldLabel: 'Project',
            displayField: 'name',
            store: 'ProjectModels',
            valueField: 'id',
            listeners: {
                select: 'onComboboxProjectSelect'
            }
        },
        {
            xtype: 'checkboxfield',
            fieldLabel: 'MainActivity',
            boxLabel: 'Yes',
            listeners: {
                change: 'onCheckboxfieldChange'
            }
        },
        {
            xtype: 'combobox',
            width: 745,
            fieldLabel: 'MainActivity',
            displayField: 'name',
            store: 'MainActivityModel',
            valueField: 'id'
        },
        {
            xtype: 'numberfield',
            width: 175,
            fieldLabel: 'SEQ'
        },
        {
            xtype: 'textfield',
            width: 745,
            fieldLabel: 'Name',
            name: 'name',
            allowBlank: false
        },
        {
            xtype: 'numberfield',
            width: 332,
            fieldLabel: 'Progress',
            minValue: 0
        },
        {
            xtype: 'numberfield',
            width: 332,
            fieldLabel: 'Budget',
            minValue: 0
        },
        {
            xtype: 'datefield',
            width: 332,
            fieldLabel: 'StartDate'
        },
        {
            xtype: 'datefield',
            width: 332,
            fieldLabel: 'EndDate'
        },
        {
            xtype: 'numberfield',
            width: 332,
            fieldLabel: 'Year',
            name: 'year',
            inputType: 'number',
            allowBlank: false,
            regex: /\d\d\d\d/
        },
        {
            xtype: 'breadcrumb',
            margin: '0 150 0 100',
            padding: 10,
            layout: 'column',
            items: [
                {
                    xtype: 'button',
                    itemId: 'saveButton',
                    margin: 5,
                    text: 'Save',
                    listeners: {
                        click: 'save'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'cancelButton',
                    margin: 5,
                    text: 'Cancel',
                    listeners: {
                        click: 'cancelEdit'
                    }
                }
            ]
        }
    ]

});