/*
 * File: app/view/Window/Form/Add/Activity.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.view.Window.Form.Add.Activity', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowformaddactivity',

    requires: [
        'LogisticSMP.view.Window.Form.Add.ActivityViewModel',
        'LogisticSMP.view.Window.Form.Add.ActivityViewController',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.toolbar.Breadcrumb',
        'Ext.button.Button'
    ],

    controller: 'windowformaddactivity',
    viewModel: {
        type: 'windowformaddactivity'
    },
    modal: true,
    height: 430,
    resizable: false,
    width: 750,
    title: 'Edit StrategicModel',
    modal: true,

    items: [
        {
            xtype: 'combobox',
            anchor: '100%',
            id:'strategic-id',
            fieldLabel: 'Strategic',
            displayField: 'name',
            labelAlign: 'right',
            store: 'StrategicModel',
            valueField: 'id',
            listConfig: {
                itemTpl: [
                    '<div data-qtip="{name}: {year}">{year} - {name}</div>'
                ]
            },
            listeners: {
                select: 'onComboboxStrategicSelect'
            }
        },
        {
            xtype: 'combobox',
            anchor: '100%',
            id:'strategy-id',
            fieldLabel: 'Strategy',
            labelAlign:'right',
            displayField: 'name',
            store: 'StrategyModel',
            valueField: 'id',
            listeners: {
                select: 'onComboboxStrategySelect'
            }
        },
        {
            xtype: 'combobox',
            anchor: '100%',
            fieldLabel: 'Project',
            displayField: 'name',
            store: 'ProjectModels',
            valueField: 'id',
            listeners: {
                select: 'onComboboxProjectSelect'
            }
        },
        {
            xtype: 'checkboxfield',
            fieldLabel: 'MainActivity',
            boxLabel: 'Yes',
            listeners: {
                change: 'onCheckboxfieldChange'
            }
        },
        {
            xtype: 'combobox',
            anchor: '100%',
            id:'project-id',
            fieldLabel: 'MainActivity',
            displayField: 'name',
            store: 'MainActivityModel',
            valueField: 'id'
        },
        {
            xtype: 'numberfield',
            anchor: '100%',
            fieldLabel: 'SEQ'
        },
        {
            xtype: 'textfield',
            anchor: '100%',
            fieldLabel: 'Name',
            name: 'name',
            allowBlank: false
        },
        {
            xtype: 'numberfield',
            anchor: '100%',
            fieldLabel: 'Progress',
            minValue: 0
        },
        {
            xtype: 'numberfield',
            anchor: '100%',
            fieldLabel: 'Budget',
            minValue: 0
        },
        {
            xtype: 'datefield',
            anchor: '100%',
            fieldLabel: 'StartDate'
        },
        {
            xtype: 'datefield',
            anchor: '100%',
            fieldLabel: 'EndDate'
        },
        {
            xtype: 'numberfield',
            width: 332,
            fieldLabel: 'Year',
            name: 'year',
            inputType: 'number',
            allowBlank: false,
            regex: /\d\d\d\d/
        },
        {
            xtype: 'breadcrumb',
            margin: '0 150 0 100',
            padding: 10,
            layout: 'column',
            items: [
                {
                    xtype: 'button',
                    itemId: 'saveButton',
                    margin: 5,
                    text: 'Save',
                    listeners: {
                        click: 'save'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'cancelButton',
                    margin: 5,
                    text: 'Cancel',
                    listeners: {
                        click: 'cancelEdit'
                    }
                }
            ]
        }
    ]

});