/*
 * File: app/view/Window/Form/Add/Project.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.view.Window.Form.Add.Project', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowformaddproject',

    requires: [
        'LogisticSMP.view.Window.Form.Add.ProjectViewController',
        'LogisticSMP.view.Window.Form.Add.ProjectViewModel',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    controller: 'windowformaddproject',
    viewModel: {
        type: 'windowformaddproject'
    },
    modal: true,
    height: 430,
    resizable: false,
    width: 750,
    title: 'จัดการโปรเจค',

    items: [
        {
            xtype: 'form',
            id: 'form1',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    id:'strategic-id',
                    fieldLabel: 'Strategic',
                    labelAlign: 'right',
                    displayField: 'name',
                    store: 'StrategicModel',
                    mode: 'local',
                    valueField: 'id',
                    listConfig: {
                            itemTpl: [
                                '<div data-qtip="{name}: {year}">{year} - {name}</div>'
                            ]
                        }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    id:'strategy-id',
                    fieldLabel: 'Strategic',
                    labelAlign: 'right',
                    displayField: 'name',
                    store: 'StrategyModel',
                    mode: 'local',
                    valueField: 'id',
                    listeners: {
                        change: 'onComboboxStrategicChange'
                    }
                    
                },
                {
                    xtype: 'numberfield',
                    id: 'project-seq',
                    anchor: '100%',
                    fieldLabel: 'Seq',
                    labelAlign: 'right',
                    name: 'seq',
                    minValue: 1
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    height: 130,
                    id: 'project-name',
                    fieldLabel: 'StrategyName',
                    labelAlign: 'right',
                    name: 'name'
                },
                {
                    xtype: 'datefield',
                    anchor: '100%',
                    id:'start-date',
                    fieldLabel: 'StartDate',
                    labelAlign: 'right'
                },
                {
                    xtype: 'datefield',
                    anchor: '100%',
                    id:'end-date',
                    fieldLabel: 'EndDate',
                    labelAlign: 'right'
                },
                {
                    xtype: 'numberfield',
                    id: 'project-progress',
                    anchor: '100%',
                    fieldLabel: 'Progress',
                    labelAlign: 'right',
                    name: 'progress',
                    minValue: 0.001
                },
                {
                    xtype: 'numberfield',
                    id: 'project-budget',
                    anchor: '100%',
                    fieldLabel: 'Bugdet',
                    labelAlign: 'right',
                    name: 'budget',
                    minValue: 1
                },
                {
                    xtype: 'button',
                    margin: '0 0 0 100',
                    text: 'บันทึก',
                    listeners: {
                        click: 'onSaveProjectClick'
                    }
                },
                {
                    xtype: 'button',
                    text: 'ยกเลิก',
                    listeners: {
                        click: 'onCancleProjectClick'
                    }
                }
            ]
        }
    ],

    onLoad: function(record) {
        console.log(record.data);
        Ext.getCmp('strategic-id').setValue(parseInt(record.data.strategic_id,10));
        Ext.getCmp('strategy-id').setValue(parseInt(record.data.strategy_id,10));
        Ext.getCmp('project-seq').setValue(record.data.seq);
        Ext.getCmp('project-name').setValue(record.data.name);
        Ext.getCmp('project-progress').setValue(record.data.progress);
        Ext.getCmp('project-budget').setValue(record.data.budget);
        Ext.getCmp('start-date').setValue(record.data.start_date);
        Ext.getCmp('end-date').setValue(record.data.end_date);
    }

});