/*
 * File: app/view/Window/Form/Add/StrategicViewController1.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.view.Window.Form.Add.StrategyViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.windowformaddstrategy',

    onButtonClick1: function(button, e, eOpts) {
    	me = this;
        var view = this.getView();
        var form = view.getComponent('form1').getForm();
        var record = view.record;
        var mode = view.mode;
        var url = "";
        var msg = "";
        console.log(view.mode);
        console.log(view.intend);
        
        if (form.isValid()) {
        	var strategic_id = Ext.getCmp('strategic-id').getValue();
        	var name = Ext.getCmp('strategy-name').getValue();
        	var seq = Ext.getCmp('strategy-seq').getValue();
        	
        	var data = {
					'seq':parseInt(seq,10),
        			'strategic_id':parseInt(strategic_id,10),
        			'name':name
        	};
        	
        	if(mode === 'add'){
        		Ext.Ajax.request({
          		  url : 'manage_strategy.php?type=add',
          		  method: 'POST',
          		  params : { 
          			  seq: parseInt(seq,10),
          			  strategic_id : parseInt(strategic_id,10),
          			  name: name
          		  },
          		  success: function (response) {
          			  console.log(response);
          		      var jsonResp = Ext.util.JSON.decode(response.responseText);
          		      
          		      if(jsonResp.status>0){
          		    	msg = "save-success";  
          		    	Ext.Msg.alert("Info","บันทึกข้อมูลเรียบร้อยแล้ว "); 
          		      }else{
          		    	Ext.Msg.alert("Info","ไม่สามารถบันทึกข้อมูลได้");
          		      }
          		  },
          		  failure: function (response) {
          			  console.log(response);
          			  var jsonResp = Ext.util.JSON.decode(response.responseText);
          		      Ext.Msg.alert("Error",jsonResp.error);
          		  }
          		});
        	}else if(mode === 'edit'){
        		console.log("in mode edit");
        		Ext.MessageBox.confirm('Confirm', 'คุณต้องการที่จะแก้ไขข้อมูล?',
    					function(cbtn, bool) {
    						if (cbtn == 'yes'){
    							Ext.Ajax.request({
    				          		  url : 'manage_strategy.php?type=edit',
    				          		  method: 'POST',
    				          		  params : { 
    				          			id: parseInt(record.data.id,10),
    				          			seq: parseInt(seq,10),
					          			strategic_id : parseInt(strategic_id,10),
					          			name: name
    				          		  },
    				          		  success: function (response) {
    				          			  console.log(response);
    				          		      var jsonResp = Ext.util.JSON.decode(response.responseText);
    				          		      
    				          		      if(jsonResp.status>0){
    				          		    	view.intend = "edit-success";  
    				          		    	Ext.Msg.alert("Info","บันทึกข้อมูลเรียบร้อยแล้ว "); 
    				          		      }else{
    				          		    	Ext.Msg.alert("Info","ไม่สามารถบันทึกข้อมูลได้");
    				          		      }
    				          		     Ext.getCmp('pagingtoolbar-strategy').moveFirst();
    				          		    	  
    				          		  },
    				          		  failure: function (response) {
    				          			  console.log(response);
    				          			  var jsonResp = Ext.util.JSON.decode(response.responseText);
    				          		      Ext.Msg.alert("Error",jsonResp.error);
    				          		  }
    				          		});
    						}
        		});
        		
        	}
        
        // close windows
        // me.close();
        view.intend = msg;
        this.getView().close();
        
        }

    },

    /* exit windows */
    onButtonClick: function(button, e, eOpts) {
        console.log(eOpts);
        this.getView().getComponent('form1').getForm().reset();
        this.getView().close();

    }

});
