/*
 * File: app/view/Window/Form/Add/StrategicViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.view.Window.Form.Add.StrategicViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.windowformaddstrategic',

    onButtonClick1: function(button, e, eOpts) {
        me = this;
        var view = this.getView();
        var form = view.getComponent('form1').getForm();
        var record = me.record;
        console.log(record);

        console.log(view.intend);
        view.intend = "save-success";

        // Valid
        console.log(form.isValid());
        if (form.isValid()) {
        	var year = Ext.getCmp('strategic-year').getValue();
        	var name = Ext.getCmp('strategic-name').getValue();
        	var data = {
        			'year':year,
        			'name':name
        	};
        	console.log(Ext.encode(data));
        	
        	Ext.Ajax.request({
        		  url : 'manage_strategic.php?type=add',
        		  method: 'POST',
        		  //yearheaders: { 'Content-Type': 'application/json' },                     
        		  params : { 
        			  year : parseInt(year,10),
        			  name: name
        		  },
        		  success: function (response) {
        			  console.log(response);
        		      var jsonResp = Ext.util.JSON.decode(response.responseText);
        		      Ext.Msg.alert("Info","UserName from Server : "+jsonResp.username);
        		  },
        		  failure: function (response) {
        			  console.log(response);
        			  var jsonResp = Ext.util.JSON.decode(response.responseText);
        		      Ext.Msg.alert("Error",jsonResp.error);
        		  }
        		});
           



        //close windows
        //me.close();
        this.getView().close();
        
        }
    },

    /* exit windows */
    onButtonClick: function(button, e, eOpts) {
        console.log(eOpts);
        this.getView().getComponent('form1').getForm().reset();
        this.getView().close();

    }

});
