/*
 * File: app/view/Window/Form/Add/Strategy.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.view.Window.Form.Add.Strategy', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowformaddstrategy',

    requires: [
        'LogisticSMP.view.Window.Form.Add.StrategyViewModel',
        'LogisticSMP.view.Window.Form.Add.StrategyViewController',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.XTemplate',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    controller: 'windowformaddstrategy',
    viewModel: {
        type: 'windowformaddstrategy'
    },
    height: 275,
    resizable: true,
    width: 616,
    title: 'จัดการกลยุทธ',

    items: [
        {
            xtype: 'form',
            id: 'form1',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    id:'strategic-id',
                    fieldLabel: 'Strategic',
                    labelAlign: 'right',
                    displayField: 'name',
                    store: 'StrategicModel',
                    mode: 'local',
                    valueField: 'id',
                    listConfig: {
                            itemTpl: [
                                '<div data-qtip="{name}: {year}">{year} - {name}</div>'
                            ]
                        }
                },
                {
                    xtype: 'numberfield',
                    id: 'strategy-seq',
                    anchor: '100%',
                    fieldLabel: 'Seq',
                    labelAlign: 'right',
                    name: 'seq',
                    minValue: 1
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    height: 130,
                    id: 'strategy-name',
                    fieldLabel: 'StrategyName',
                    labelAlign: 'right',
                    name: 'name'
                },
                {
                    xtype: 'button',
                    margin: '0 0 0 100',
                    text: 'บันทึก',
                    listeners: {
                        click: 'onButtonClick1'
                    }
                },
                {
                    xtype: 'button',
                    text: 'ยกเลิก',
                    listeners: {
                        click: 'onButtonClick'
                    }
                }
            ]
        }
    ],

    onLoad: function(record) {
        console.log(record.data);
        console.log(record.data.strategic_id);
        Ext.getCmp('strategy-name').setValue(record.data.name);
        Ext.getCmp('strategic-id').setValue(record.data.strategic_id);
        Ext.getCmp('strategy-seq').setValue(record.data.seq);
    }

});