/*
 * File: app/view/Window/Form/Add/Strategic.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.view.Window.Form.Add.Strategic', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowformaddstrategic',

    requires: [
        'LogisticSMP.view.Window.Form.Add.StrategicViewModel',
        'LogisticSMP.view.Window.Form.Add.StrategicViewController',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    controller: 'windowformaddstrategic',
    viewModel: {
        type: 'windowformaddstrategic'
    },
    height: 252,
    resizable: false,
    width: 616,
    title: 'จัดการกลยุทธ',

    items: [
        {
            xtype: 'form',
            id: 'form1',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    id: 'strategic-year',
                    width: 586,
                    fieldLabel: 'Year',
                    labelAlign: 'right',
                    name: 'year',
                    displayField: 'year',
                    queryMode: 'local',
                    store: 'YearArrayStore',
                    valueField: 'id'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    height: 130,
                    id: 'strategic-seq',
                    fieldLabel: 'Seq',
                    labelAlign: 'right',
                    name: 'seq'
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    height: 130,
                    id: 'strategic-name',
                    fieldLabel: 'Name',
                    labelAlign: 'right',
                    name: 'name'
                },
                {
                    xtype: 'button',
                    margin: '0 0 0 100',
                    text: 'บันทึก',
                    listeners: {
                        click: 'onButtonClick1'
                    }
                },
                {
                    xtype: 'button',
                    text: 'ยกเลิก',
                    listeners: {
                        click: 'onButtonClick'
                    }
                }
            ]
        }
    ],

    onLoad: function(record) {
        console.log(record);
        Ext.getCmp('strategic-name').setValue(record.data.name);
    }

});