/*
 * File: app/view/Logistic/Overview.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LogisticSMP.view.Logistic.Overview', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.logisticoverview',

    requires: [
        'LogisticSMP.view.Logistic.OverviewViewModel',
        'Ext.chart.PolarChart',
        'Ext.chart.series.Gauge',
        'Ext.chart.series.sprite.PieSlice',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar',
        'Ext.chart.interactions.PanZoom'
    ],

    viewModel: {
        type: 'logisticoverview'
    },
    itemId: 'contentPanel1',
    anchorSize: '100% 20%',
    title: 'หน้าหลัก',
    titleAlign: 'center',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'panel',
            anchor: '100% 50%',
            flex: 1,
            margins: '0 10 10 0',
            height: '',
            collapseFirst: false,
            collapsible: false,
            title: 'ภาพรวมโครงการ',
            titleAlign: 'center',
            layout: {
                type: 'hbox',
                align: 'stretchmax',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'polar',
                    flex: 1,
                    shadow: true,
                    border: false,
                    height: 198,
                    ui: 'light',
                    width: 208,
                    header: false,
                    headerPosition: 'bottom',
                    title: 'overview',
                    titleAlign: 'center',
                    titleCollapse: false,
                    animation: true,
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    store: 'GaugeStore',
                    innerPadding: 15,
                    radius: 45,
                    series: [
                        {
                            type: 'gauge',
                            renderer: function(sprite, record, attributes, index, store) {

                                console.log(attributes);
                                return attributes;

                            },
                            showInLegend: true,
                            donut: 30,
                            field: 'overview',
                            maximum: 10,
                            minimum: 1,
                            needle: true,
                            sectors: [
                                {
                                    end: 20,
                                    label: 'Cold',
                                    color: 'aqua'
                                },
                                {
                                    end: 60,
                                    label: 'Temp.',
                                    color: 'lightgray',
                                    style: {
                                        strokeStyle: 'black',
                                        strokeOpacity: 1,
                                        lineWidth: 1
                                    }
                                },
                                {
                                    label: 'Hot',
                                    color: 'tomato'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'polar',
                    flex: 1,
                    ui: 'light',
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    store: 'GaugeStore',
                    series: [
                        {
                            type: 'gauge',
                            donut: 30,
                            field: 'project',
                            needle: true
                        }
                    ]
                },
                {
                    xtype: 'polar',
                    flex: 1,
                    ui: 'light',
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    store: 'GaugeStore',
                    series: [
                        {
                            type: 'gauge',
                            donut: 30,
                            field: 'budget',
                            needle: true,
                            needleWidth: 7
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 2,
            collapsible: false,
            title: 'ภาพรวมความก้าวหน้ารายยุทธศาสตร์',
            titleAlign: 'center',
            layout: {
                type: 'vbox',
                align: 'stretchmax'
            },
            dockedItems: [
                {
                    xtype: 'cartesian',
                    flex: -1,
                    dock: 'top',
                    height: 429,
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    store: 'BarCharOverViewStore',
                    axes: [
                        {
                            type: 'category',
                            fields: [
                                'name'
                            ],
                            grid: true,
                            position: 'bottom'
                        },
                        {
                            type: 'numeric',
                            fields: [
                                'Current',
                                'progress'
                            ],
                            grid: {
                                odd: {
                                    fill: '#e8e8e8'
                                }
                            },
                            position: 'left'
                        }
                    ],
                    series: [
                        {
                            type: 'bar',
                            xField: 'name',
                            yField: [
                                'Current',
                                'progress'
                            ],
                            stacked: false
                        }
                    ],
                    interactions: [
                        {
                            type: 'panzoom'
                        }
                    ]
                }
            ]
        }
    ]

});